// <auto-generated>
// Written by the #269 data build from the Truck Simulator Wiki (cities, companies), ProMods' city list
// and GeoNames (CC BY 4.0). Regenerate rather than edit: the source tables are the record.
// </auto-generated>
namespace TruckSimDispatcher.Services;

internal static partial class Ets2Data
{
    /// <summary>Where each country sits: the median of its populated places, for distances to a city we
    /// do not know. Rough by design, the same as the US state centroids.</summary>
    internal static readonly Dictionary<string, (double Lat, double Lon)> Centres = new(StringComparer.OrdinalIgnoreCase)
    {
        ["AD"] = (42.54, 1.52),
        ["AL"] = (40.94, 19.96),
        ["AT"] = (47.58, 14.74),
        ["AX"] = (60.21, 20.05),
        ["BA"] = (44.53, 17.96),
        ["BE"] = (50.71, 4.58),
        ["BG"] = (42.77, 25.09),
        ["CH"] = (47.09, 8.04),
        ["CY"] = (34.96, 33.2),
        ["CZ"] = (49.75, 15.77),
        ["DE"] = (50.62, 9.92),
        ["DK"] = (55.75, 10.31),
        ["EE"] = (58.93, 25.43),
        ["EG"] = (30.3, 31.32),
        ["ES"] = (41.04, -3.36),
        ["FI"] = (61.42, 24.82),
        ["FO"] = (62.11, -6.78),
        ["FR"] = (47.44, 2.44),
        ["GE"] = (42.13, 42.65),
        ["GG"] = (49.46, -2.57),
        ["GL"] = (66.97, -51.46),
        ["GR"] = (39.14, 22.82),
        ["HR"] = (45.44, 16.37),
        ["HU"] = (47.39, 19.48),
        ["IE"] = (53.2, -7.58),
        ["IL"] = (32.32, 35.0),
        ["IM"] = (54.2, -4.54),
        ["IQ"] = (34.69, 44.4),
        ["IS"] = (64.43, -21.28),
        ["IT"] = (44.44, 11.54),
        ["JE"] = (49.22, -2.1),
        ["JO"] = (32.1, 35.79),
        ["LB"] = (33.81, 35.66),
        ["LI"] = (47.19, 9.52),
        ["LT"] = (55.25, 23.85),
        ["LU"] = (49.67, 6.12),
        ["LV"] = (56.9, 24.52),
        ["MC"] = (43.74, 7.42),
        ["MD"] = (47.07, 28.76),
        ["ME"] = (42.46, 19.12),
        ["MK"] = (41.65, 21.38),
        ["MT"] = (35.9, 14.46),
        ["NL"] = (52.05, 5.63),
        ["NO"] = (60.57, 10.05),
        ["PL"] = (51.19, 19.55),
        ["PS"] = (32.02, 35.17),
        ["PT"] = (39.69, -8.6),
        ["RO"] = (45.78, 25.19),
        ["RS"] = (44.82, 20.35),
        ["RU"] = (54.42, 45.83),
        ["SA"] = (25.16, 43.62),
        ["SE"] = (58.63, 15.0),
        ["SI"] = (46.26, 15.01),
        ["SJ"] = (74.57, 3.46),
        ["SK"] = (48.7, 18.43),
        ["SY"] = (35.07, 36.57),
        ["TR"] = (38.26, 34.71),
        ["UA"] = (48.42, 31.81),
        ["UK"] = (52.45, -1.68),
        ["XK"] = (42.55, 20.79),
    };

    /// <summary>
    /// ETS2's freight markets, the same columns as <see cref="Markets"/>: City|CC|Tier|Reset|Source|Strong.
    ///
    /// The tier comes off how many companies a city has in the game (the wiki's count): 8 or more is tier 1,
    /// 5 to 7 is tier 2, fewer is tier 3. Tiers 1 and 2 have the services to sit a weekly rest. The source is
    /// the map that adds the country (base game or the DLC), or ProMods for the cities ProMods adds, which
    /// start at tier 3 until somebody runs them. No strong divisions yet: the US ones came from play.
    /// </summary>
    internal const string MarketTable = """
        Andorra la Vella|AD|3|0|ProMods|
        Durrës|AL|3|0|West Balkans|
        Fier|AL|3|0|West Balkans|
        Tiranë|AL|2|1|West Balkans|
        Vlorë|AL|2|1|West Balkans|
        Amstetten|AT|3|0|ProMods|
        Bischofshofen|AT|3|0|ProMods|
        Graz|AT|2|1|Base game|
        Innsbruck|AT|3|0|Base game|
        Klagenfurt am Wörthersee|AT|2|1|Base game|
        Leoben|AT|3|0|ProMods|
        Linz|AT|3|0|Base game|
        Saalfelden|AT|3|0|ProMods|
        Salzburg|AT|2|1|Base game|
        Stockerau|AT|3|0|ProMods|
        Wien|AT|2|1|Base game|
        Winklern|AT|3|0|ProMods|
        Geta|AX|3|0|ProMods|
        Godby|AX|3|0|ProMods|
        Mariehamn|AX|3|0|ProMods|
        Banja Luka|BA|1|1|West Balkans|
        Bihać|BA|3|0|West Balkans|
        Karakaj|BA|3|0|West Balkans|
        Mostar|BA|3|0|West Balkans|
        Sarajevo|BA|3|0|West Balkans|
        Tuzla|BA|2|1|West Balkans|
        Zenica|BA|2|1|West Balkans|
        Antwerpen|BE|3|0|Base game|
        Brussel|BE|2|1|Base game|
        Liège|BE|3|0|Base game|
        Blagoevgrad|BG|3|0|ProMods|
        Burgas|BG|2|1|Road to the Black Sea|
        Dobrich|BG|3|0|ProMods|
        Karlovo|BG|3|0|Road to the Black Sea|
        Kozloduy|BG|3|0|Road to the Black Sea|
        Montana|BG|3|0|ProMods|
        Pernik|BG|3|0|Road to the Black Sea|
        Pirdop|BG|3|0|Road to the Black Sea|
        Pleven|BG|2|1|Road to the Black Sea|
        Plovdiv|BG|3|0|Road to the Black Sea|
        Razgrad|BG|3|0|ProMods|
        Ruse|BG|2|1|Road to the Black Sea|
        Shumen|BG|3|0|ProMods|
        Silistra|BG|3|0|ProMods|
        Sofia|BG|1|1|Road to the Black Sea|
        Varna|BG|3|0|Road to the Black Sea|
        Veliko Tarnovo|BG|3|0|Road to the Black Sea|
        Vidin|BG|3|0|ProMods|
        Bern|CH|2|1|Base game|
        Genève|CH|2|1|Base game|
        Zürich|CH|2|1|Base game|
        Larnaca|CY|3|0|ProMods|
        Limassol|CY|3|0|ProMods|
        Nicosia|CY|3|0|ProMods|
        Paphos|CY|3|0|ProMods|
        Brno|CZ|3|0|Base game|
        Jihlava|CZ|3|0|ProMods|
        Mladá Boleslav|CZ|3|0|ProMods|
        Olomouc|CZ|3|0|ProMods|
        Ostrava|CZ|3|0|Base game|
        Praha|CZ|2|1|Base game|
        Anklam|DE|3|0|ProMods|
        Bad Oeynhausen|DE|3|0|ProMods|
        Berlin|DE|2|1|Base game|
        Bonn|DE|3|0|ProMods|
        Bremen|DE|2|1|Base game|
        Bremerhaven|DE|3|0|ProMods|
        Burg auf Fehmarn|DE|3|0|ProMods|
        Chemnitz|DE|3|0|ProMods|
        Dortmund|DE|2|1|Base game|
        Dresden|DE|2|1|Base game|
        Duisburg|DE|2|1|Base game|
        Düsseldorf|DE|2|1|Base game|
        Erfurt|DE|3|0|Base game|
        Flensburg|DE|3|0|ProMods|
        Forst|DE|3|0|ProMods|
        Frankfurt am Main|DE|1|1|Base game|
        Halle|DE|3|0|ProMods|
        Hamburg|DE|2|1|Base game|
        Hannover|DE|2|1|Base game|
        Heilbronn|DE|3|0|ProMods|
        Kassel|DE|2|1|Base game|
        Kiel|DE|2|1|Base game|
        Koblenz|DE|3|0|ProMods|
        Köln|DE|2|1|Base game|
        Leipzig|DE|2|1|Base game|
        Magdeburg|DE|2|1|Base game|
        Mainz|DE|3|0|ProMods|
        Mannheim|DE|2|1|Base game|
        München|DE|2|1|Base game|
        Nürnberg|DE|1|1|Base game|
        Oberhausen|DE|3|0|ProMods|
        Osnabrück|DE|3|0|Base game|
        Puttgarden|DE|3|0|ProMods|
        Rostock|DE|2|1|Base game|
        Soltau|DE|3|0|ProMods|
        Stuttgart|DE|3|0|Base game|
        Travemünde|DE|3|0|Base game|
        Uelzen|DE|3|0|ProMods|
        Werlte|DE|3|0|Base game|
        Wiesbaden|DE|3|0|ProMods|
        Winsen|DE|3|0|Base game|
        Aalborg|DK|2|1|Scandinavia|
        Aarhus|DK|2|1|Scandinavia|
        Esbjerg|DK|2|1|Scandinavia|
        Frederikshavn|DK|3|0|Scandinavia|
        Gedser|DK|3|0|Scandinavia|
        Herning|DK|3|0|ProMods|
        Hirtshals|DK|3|0|Scandinavia|
        Holstebro|DK|3|0|ProMods|
        Kolding|DK|3|0|ProMods|
        København|DK|2|1|Scandinavia|
        Odense|DK|2|1|Scandinavia|
        Padborg|DK|3|0|ProMods|
        Rødbyhavn|DK|3|0|ProMods|
        Rønne|DK|3|0|ProMods|
        Vesterø Havn|DK|3|0|ProMods|
        Viborg|DK|3|0|ProMods|
        Haapsalu|EE|3|0|ProMods|
        Kunda|EE|3|0|Beyond the Baltic Sea|
        Kuressaare|EE|3|0|ProMods|
        Kärdla|EE|3|0|ProMods|
        Narva|EE|3|0|Beyond the Baltic Sea|
        Paldiski|EE|3|0|Beyond the Baltic Sea|
        Pärnu|EE|2|1|Beyond the Baltic Sea|
        Rakvere|EE|3|0|ProMods|
        Tallinn|EE|1|1|Beyond the Baltic Sea|
        Tartu|EE|1|1|Beyond the Baltic Sea|
        Valga|EE|3|0|ProMods|
        A Coruña|ES|1|1|Iberia|
        Albacete|ES|2|1|Iberia|
        Algeciras|ES|2|1|Iberia|
        Almaraz|ES|3|0|Iberia|
        Almería|ES|2|1|Iberia|
        Badajoz|ES|2|1|Iberia|
        Bailén|ES|3|0|Iberia|
        Barcelona|ES|1|1|Iberia|
        Bilbao|ES|2|1|Iberia|
        Burgos|ES|2|1|Iberia|
        Canfranc-Estación|ES|3|0|ProMods|
        Ciudad Real|ES|3|0|Iberia|
        Contreras|ES|3|0|ProMods|
        Córdoba|ES|2|1|Iberia|
        El Ejido|ES|3|0|Iberia|
        Gijón|ES|3|0|Iberia|
        Granada|ES|3|0|Iberia|
        Huelva|ES|3|0|Iberia|
        Huesca|ES|3|0|ProMods|
        Jaca|ES|3|0|ProMods|
        La Jonquera|ES|3|0|ProMods|
        León|ES|3|0|Iberia|
        Lleida|ES|3|0|Iberia|
        Llívia|ES|3|0|ProMods|
        Madrid|ES|1|1|Iberia|
        Mengíbar|ES|3|0|Iberia|
        Murcia|ES|2|1|Iberia|
        Málaga|ES|2|1|Iberia|
        Navia|ES|3|0|Iberia|
        O Barco|ES|3|0|Iberia|
        Pamplona|ES|3|0|Iberia|
        Port de Sagunt|ES|3|0|Iberia|
        Puertollano|ES|3|0|Iberia|
        Salamanca|ES|2|1|Iberia|
        Santander|ES|2|1|Iberia|
        Sevilla|ES|1|1|Iberia|
        Soria|ES|3|0|Iberia|
        Tarragona|ES|3|0|Iberia|
        Teruel|ES|3|0|Iberia|
        Valladolid|ES|2|1|Iberia|
        València|ES|2|1|Iberia|
        Vandellòs|ES|3|0|Iberia|
        Vigo|ES|2|1|Iberia|
        Vila-real|ES|3|0|Iberia|
        Zaragoza|ES|2|1|Iberia|
        Alajärvi|FI|3|0|ProMods|
        Helsinki|FI|1|1|Beyond the Baltic Sea|
        Ivalo|FI|2|1|Beyond the Baltic Sea|
        Joensuu|FI|2|1|Beyond the Baltic Sea|
        Jyväskylä|FI|2|1|Beyond the Baltic Sea|
        Kajaani|FI|2|1|Beyond the Baltic Sea|
        Kaustinen|FI|3|0|ProMods|
        Kemi|FI|3|0|ProMods|
        Kemijärvi|FI|3|0|ProMods|
        Kittilä|FI|3|0|ProMods|
        Kokkola|FI|1|1|Beyond the Baltic Sea|
        Kotka|FI|2|1|Beyond the Baltic Sea|
        Kouvola|FI|2|1|Beyond the Baltic Sea|
        Kristiinankaupunki|FI|3|0|ProMods|
        Kuopio|FI|2|1|Beyond the Baltic Sea|
        Kuusamo|FI|2|1|Beyond the Baltic Sea|
        Kärsämäki|FI|3|0|ProMods|
        Lahti|FI|3|0|Beyond the Baltic Sea|
        Lappeenranta|FI|2|1|Beyond the Baltic Sea|
        Loviisa|FI|3|0|Beyond the Baltic Sea|
        Mikkeli|FI|2|1|Beyond the Baltic Sea|
        Muonio|FI|3|0|ProMods|
        Naantali|FI|3|0|Beyond the Baltic Sea|
        Olkiluoto|FI|3|0|Beyond the Baltic Sea|
        Oulu|FI|1|1|Beyond the Baltic Sea|
        Pello|FI|3|0|ProMods|
        Pori|FI|2|1|Beyond the Baltic Sea|
        Rovaniemi|FI|3|0|Beyond the Baltic Sea|
        Savonlinna|FI|3|0|ProMods|
        Seinäjoki|FI|3|0|ProMods|
        Sodankylä|FI|3|0|ProMods|
        Tampere|FI|2|1|Beyond the Baltic Sea|
        Tornio|FI|2|1|Beyond the Baltic Sea|
        Turku|FI|2|1|Beyond the Baltic Sea|
        Utsjoki|FI|3|0|ProMods|
        Vaasa|FI|2|1|Beyond the Baltic Sea|
        Vantaa|FI|3|0|ProMods|
        Varkaus|FI|3|0|ProMods|
        Viitasaari|FI|3|0|ProMods|
        Ylivieska|FI|3|0|ProMods|
        Klaksvík|FO|3|0|ProMods|
        Tórshavn|FO|3|0|ProMods|
        Ajaccio|FR|2|1|Base game|
        Bastia|FR|2|1|Base game|
        Bayonne|FR|3|0|Base game|
        Bonifacio|FR|3|0|Base game|
        Bordeaux|FR|1|1|Base game|
        Bourges|FR|3|0|Base game|
        Brest|FR|2|1|Base game|
        Calais|FR|3|0|Base game|
        Calvi|FR|3|0|Base game|
        Cherbourg-en-Cotentin|FR|3|0|ProMods|
        Civaux|FR|3|0|Base game|
        Clermont-Ferrand|FR|2|1|Base game|
        Coquelles|FR|3|0|ProMods|
        Dax|FR|3|0|ProMods|
        Dijon|FR|3|0|Base game|
        Foix|FR|3|0|ProMods|
        Golfech|FR|3|0|Base game|
        Granville|FR|3|0|ProMods|
        L'Île-Rousse|FR|3|0|Base game|
        La Rochelle|FR|2|1|Base game|
        Lacq|FR|3|0|Base game|
        Le Havre|FR|2|1|Base game|
        Le Mans|FR|1|1|Base game|
        Lille|FR|3|0|Base game|
        Limoges|FR|2|1|Base game|
        Lyon|FR|2|1|Base game|
        Marseille|FR|1|1|Base game|
        Metz|FR|3|0|Base game|
        Montpellier|FR|1|1|Base game|
        Mulhouse|FR|3|0|ProMods|
        Mâcon|FR|3|0|ProMods|
        Nantes|FR|2|1|Base game|
        Narbonne|FR|3|0|ProMods|
        Nice|FR|2|1|Base game|
        Orléans|FR|3|0|ProMods|
        Paluel|FR|3|0|Base game|
        Paris|FR|2|1|Base game|
        Perpignan|FR|3|0|ProMods|
        Port-Vendres|FR|3|0|ProMods|
        Porto-Vecchio|FR|3|0|Base game|
        Reims|FR|3|0|Base game|
        Rennes|FR|2|1|Base game|
        Roscoff|FR|3|0|Base game|
        Saint-Alban-du-Rhône|FR|3|0|Base game|
        Saint-Laurent|FR|3|0|Base game|
        Strasbourg|FR|2|1|Base game|
        Toulouse|FR|3|0|Base game|
        Valenciennes|FR|3|0|ProMods|
        Akhaltsikhe|GE|3|0|ProMods|
        Batumi|GE|3|0|ProMods|
        Borjomi|GE|3|0|ProMods|
        Gori|GE|3|0|ProMods|
        Khashuri|GE|3|0|ProMods|
        Kutaisi|GE|3|0|ProMods|
        Poti|GE|3|0|ProMods|
        Tbilisi|GE|3|0|ProMods|
        Zeni|GE|3|0|ProMods|
        St. Peter Port|GG|3|0|ProMods|
        Nuuk|GL|3|0|ProMods|
        Alexandroupoli|GR|3|0|ProMods|
        Argostoli|GR|2|1|Greece|
        Athina|GR|1|1|Greece|
        Chania|GR|3|0|Greece|
        Chios|GR|3|0|Greece|
        Evzonoi|GR|3|0|ProMods|
        Igoumenitsa|GR|3|0|ProMods|
        Ioannina|GR|3|0|Greece|
        Irakleio|GR|3|0|Greece|
        Kalamata|GR|2|1|Greece|
        Kavala|GR|2|1|Greece|
        Komotiní|GR|3|0|ProMods|
        Lamia|GR|3|0|Greece|
        Larisa|GR|2|1|Greece|
        Mytilini|GR|2|1|Greece|
        Patra|GR|3|0|Greece|
        Ptolemaida|GR|3|0|ProMods|
        Rodos|GR|3|0|Greece|
        Serres|GR|3|0|ProMods|
        Thessaloniki|GR|1|1|Greece|
        Trikala|GR|3|0|Greece|
        Dubrovnik|HR|3|0|ProMods|
        Osijek|HR|2|1|West Balkans|
        Ploče|HR|3|0|ProMods|
        Rijeka|HR|2|1|West Balkans|
        Split|HR|3|0|West Balkans|
        Zadar|HR|2|1|West Balkans|
        Zagreb|HR|2|1|West Balkans|
        Budapest|HU|3|0|Going East!|
        Debrecen|HU|3|0|Going East!|
        Győr|HU|3|0|ProMods|
        Kecskemét|HU|3|0|ProMods|
        Pécs|HU|3|0|Going East!|
        Szeged|HU|3|0|Going East!|
        Szombathely|HU|3|0|ProMods|
        Sümeg|HU|3|0|ProMods|
        Vásárosnamény|HU|3|0|ProMods|
        Dublin|IE|3|0|ProMods|
        Galway|IE|3|0|ProMods|
        Kilkenny|IE|3|0|ProMods|
        Limerick|IE|3|0|ProMods|
        Sligo|IE|3|0|ProMods|
        Waterford|IE|3|0|ProMods|
        Wexford|IE|3|0|ProMods|
        Douglas|IM|3|0|ProMods|
        Ramsey|IM|3|0|ProMods|
        Akranes|IS|3|0|ProMods|
        Akureyri|IS|3|0|ProMods|
        Blönduós|IS|3|0|ProMods|
        Bolungarvík|IS|3|0|ProMods|
        Borgarnes|IS|3|0|ProMods|
        Hólmavík|IS|3|0|ProMods|
        Höfn|IS|3|0|ProMods|
        Keflavík|IS|3|0|ProMods|
        Krafla|IS|3|0|ProMods|
        Norðurfjörður|IS|3|0|ProMods|
        Reykjavik|IS|3|0|ProMods|
        Reyðarfjörður|IS|3|0|ProMods|
        Selfoss|IS|3|0|ProMods|
        Seyðisfjörður|IS|3|0|ProMods|
        Stykkishólmur|IS|3|0|ProMods|
        Varmahlíð|IS|3|0|ProMods|
        Vestmannaeyjar|IS|3|0|ProMods|
        Vík|IS|3|0|ProMods|
        Ísafjörður|IS|3|0|ProMods|
        Ólafsvík|IS|3|0|ProMods|
        Þorlákshöfn|IS|3|0|ProMods|
        Ancona|IT|2|1|Base game|
        Bari|IT|2|1|Base game|
        Bologna|IT|2|1|Base game|
        Cagliari|IT|2|1|Base game|
        Cassino|IT|3|0|Base game|
        Catania|IT|1|1|Base game|
        Catanzaro|IT|2|1|Base game|
        Firenze|IT|2|1|Base game|
        Genova|IT|2|1|Base game|
        Livorno|IT|2|1|Base game|
        Messina|IT|3|0|Base game|
        Milano|IT|1|1|Base game|
        Napoli|IT|1|1|Base game|
        Olbia|IT|2|1|Base game|
        Palermo|IT|2|1|Base game|
        Parma|IT|2|1|Base game|
        Pescara|IT|1|1|Base game|
        Roma|IT|1|1|Base game|
        Sassari|IT|2|1|Base game|
        Siracusa|IT|3|0|ProMods|
        Suzzara|IT|3|0|Base game|
        Taranto|IT|1|1|Base game|
        Terni|IT|3|0|Base game|
        Torino|IT|3|0|Base game|
        Trieste|IT|3|0|Base game|
        Venezia|IT|3|0|Base game|
        Verona|IT|3|0|Base game|
        Villa San Giovanni|IT|3|0|Base game|
        Saint Helier|JE|3|0|ProMods|
        Trinity|JE|3|0|ProMods|
        Kaunas|LT|2|1|Beyond the Baltic Sea|
        Klaipėda|LT|2|1|Beyond the Baltic Sea|
        Mažeikiai|LT|3|0|Beyond the Baltic Sea|
        Panevėžys|LT|3|0|Beyond the Baltic Sea|
        Tauragė|LT|3|0|ProMods|
        Ukmergė|LT|3|0|ProMods|
        Utena|LT|2|1|Beyond the Baltic Sea|
        Vilnius|LT|1|1|Beyond the Baltic Sea|
        Šiauliai|LT|3|0|Beyond the Baltic Sea|
        Luxembourg|LU|2|1|Base game|
        Balvi|LV|3|0|ProMods|
        Daugavpils|LV|2|1|Beyond the Baltic Sea|
        Gulbene|LV|3|0|ProMods|
        Jēkabpils|LV|3|0|ProMods|
        Kolka|LV|3|0|ProMods|
        Liepāja|LV|2|1|Beyond the Baltic Sea|
        Rēzekne|LV|3|0|Beyond the Baltic Sea|
        Rīga|LV|1|1|Beyond the Baltic Sea|
        Valka|LV|3|0|ProMods|
        Valmiera|LV|2|1|Beyond the Baltic Sea|
        Ventspils|LV|2|1|Beyond the Baltic Sea|
        Monaco City|MC|3|0|ProMods|
        Bălți|MD|3|0|ProMods|
        Chişinǎu|MD|3|0|ProMods|
        Giurgiulești|MD|3|0|ProMods|
        Bar|ME|3|0|ProMods|
        Bijelo Polje|ME|2|1|West Balkans|
        Nikšić|ME|3|0|West Balkans|
        Podgorica|ME|2|1|West Balkans|
        Bitola|MK|3|0|West Balkans|
        Skopje|MK|1|1|West Balkans|
        Il-Belt Valletta|MT|3|0|ProMods|
        Amsterdam|NL|2|1|Base game|
        Arnhem|NL|3|0|ProMods|
        Eindhoven|NL|3|0|Base game|
        Groningen|NL|2|1|Base game|
        Moerdijk|NL|3|0|ProMods|
        Rotterdam|NL|2|1|Base game|
        Zwolle|NL|3|0|ProMods|
        Alta|NO|3|0|Scandinavia|
        Andenes|NO|3|0|Scandinavia|
        Ballangen|NO|3|0|ProMods|
        Bardufoss|NO|3|0|ProMods|
        Bergen|NO|2|1|Scandinavia|
        Berlevåg|NO|3|0|ProMods|
        Bidjovagge|NO|3|0|ProMods|
        Bodø|NO|2|1|Scandinavia|
        Båtsfjord|NO|3|0|ProMods|
        Dombås|NO|3|0|Scandinavia|
        Drammen|NO|3|0|ProMods|
        Fauske|NO|3|0|ProMods|
        Finnsness|NO|3|0|ProMods|
        Grong|NO|3|0|ProMods|
        Hamar|NO|2|1|Scandinavia|
        Hammerfest|NO|3|0|ProMods|
        Honningsvåg|NO|3|0|Scandinavia|
        Karasjok|NO|3|0|ProMods|
        Kautokeino|NO|3|0|ProMods|
        Kirkenes|NO|3|0|ProMods|
        Kjøllefjord|NO|3|0|ProMods|
        Kristiansand|NO|2|1|Scandinavia|
        Kristiansund|NO|3|0|Scandinavia|
        Lakselv|NO|3|0|ProMods|
        Lebesby|NO|3|0|ProMods|
        Lillehammer|NO|2|1|Scandinavia|
        Mehamn|NO|3|0|ProMods|
        Mo i Rana|NO|3|0|Scandinavia|
        Molde|NO|3|0|ProMods|
        Mosjøen|NO|3|0|ProMods|
        Namsskogan|NO|3|0|ProMods|
        Narvik|NO|2|1|Scandinavia|
        Oppdal|NO|3|0|ProMods|
        Orkanger|NO|3|0|ProMods|
        Oslo|NO|1|1|Scandinavia|
        Otta|NO|3|0|ProMods|
        Setermoen|NO|3|0|ProMods|
        Stavanger|NO|2|1|Scandinavia|
        Steinkjer|NO|3|0|Scandinavia|
        Strostlett|NO|3|0|ProMods|
        Svolvær|NO|3|0|Scandinavia|
        Tana Bru|NO|3|0|ProMods|
        Trofors|NO|3|0|ProMods|
        Tromsø|NO|2|1|Scandinavia|
        Trondheim|NO|1|1|Scandinavia|
        Vadsø|NO|3|0|ProMods|
        Vardø|NO|3|0|ProMods|
        Verdalsøra|NO|3|0|ProMods|
        Vevelstad|NO|3|0|ProMods|
        Ålesund|NO|2|1|Scandinavia|
        Åndalsnes|NO|3|0|ProMods|
        Augustów|PL|3|0|ProMods|
        Białystok|PL|3|0|Base game|
        Bielsko-Biała|PL|3|0|ProMods|
        Bydgoszcz|PL|3|0|ProMods|
        Chełm|PL|3|0|ProMods|
        Elbląg|PL|3|0|ProMods|
        Ełk|PL|3|0|ProMods|
        Gdańsk|PL|2|1|Base game|
        Gdynia|PL|3|0|ProMods|
        Gorzów Wielkopolski|PL|3|0|ProMods|
        Grudziądz|PL|3|0|ProMods|
        Katowice|PL|3|0|Base game|
        Kielce|PL|3|0|ProMods|
        Koszalin|PL|3|0|ProMods|
        Kraków|PL|3|0|Base game|
        Krasnystaw|PL|3|0|ProMods|
        Lublin|PL|3|0|Base game|
        Mrągowo|PL|3|0|ProMods|
        Nowogard|PL|3|0|ProMods|
        Olsztyn|PL|2|1|Base game|
        Opole|PL|3|0|ProMods|
        Ostrołęka|PL|3|0|ProMods|
        Ostrów Mazowiecka|PL|3|0|ProMods|
        Piotrków Trybunalski|PL|3|0|ProMods|
        Piątnica|PL|3|0|ProMods|
        Poznań|PL|3|0|Base game|
        Przemyśl|PL|3|0|ProMods|
        Płock|PL|3|0|ProMods|
        Radom|PL|3|0|ProMods|
        Rzeszów|PL|3|0|ProMods|
        Sanok|PL|3|0|ProMods|
        Siedlce|PL|3|0|ProMods|
        Suwałki|PL|3|0|ProMods|
        Szczecin|PL|3|0|Base game|
        Wadowice|PL|3|0|ProMods|
        Warszawa|PL|3|0|Base game|
        Wałcz|PL|3|0|ProMods|
        Wrocław|PL|3|0|Base game|
        Zamość|PL|3|0|ProMods|
        Zgorzelec|PL|3|0|ProMods|
        Łódź|PL|3|0|Base game|
        Świnoujście|PL|3|0|ProMods|
        Beja|PT|3|0|Iberia|
        Coimbra|PT|3|0|Iberia|
        Cortiçadas de Lavre|PT|3|0|Iberia|
        Faro|PT|3|0|Iberia|
        Guarda|PT|3|0|Iberia|
        Lisboa|PT|1|1|Iberia|
        Olhão|PT|3|0|Iberia|
        Ponte de Sor|PT|3|0|Iberia|
        Porto|PT|2|1|Iberia|
        Setúbal|PT|3|0|Iberia|
        Sines|PT|2|1|Iberia|
        Évora|PT|3|0|Iberia|
        Bacău|RO|3|0|Road to the Black Sea|
        Brașov|RO|2|1|Road to the Black Sea|
        București|RO|1|1|Road to the Black Sea|
        Cernavodă|RO|3|0|Road to the Black Sea|
        Cluj-Napoca|RO|2|1|Road to the Black Sea|
        Constanța|RO|2|1|Road to the Black Sea|
        Craiova|RO|3|0|Road to the Black Sea|
        Călărași|RO|3|0|Road to the Black Sea|
        Galați|RO|1|1|Road to the Black Sea|
        Hunedoara|RO|2|1|Road to the Black Sea|
        Iași|RO|2|1|Road to the Black Sea|
        Mangalia|RO|3|0|Road to the Black Sea|
        Pitești|RO|2|1|Road to the Black Sea|
        Reșița|RO|3|0|Road to the Black Sea|
        Satu Mare|RO|3|0|ProMods|
        Sebeș|RO|3|0|ProMods|
        Sibiu|RO|3|0|ProMods|
        Timișoara|RO|2|1|Road to the Black Sea|
        Tulcea|RO|3|0|ProMods|
        Târgu Mureș|RO|3|0|Road to the Black Sea|
        Beograd|RS|1|1|West Balkans|
        Kragujevac|RS|2|1|West Balkans|
        Niš|RS|1|1|West Balkans|
        Novi Sad|RS|1|1|West Balkans|
        Gusev|RU|3|0|ProMods|
        Kaliningrad|RU|2|1|Beyond the Baltic Sea|
        Kandalaksha|RU|3|0|ProMods|
        Luga|RU|3|0|Beyond the Baltic Sea|
        Murmansk|RU|3|0|ProMods|
        Nikel|RU|3|0|ProMods|
        Pskov|RU|2|1|Beyond the Baltic Sea|
        Saint Petersburg|RU|1|1|Beyond the Baltic Sea|
        Sosnovy Bor|RU|3|0|Beyond the Baltic Sea|
        Verkhnetulomsky|RU|3|0|ProMods|
        Vyborg|RU|3|0|Beyond the Baltic Sea|
        Zelenogradsk|RU|3|0|ProMods|
        Arvidsjaur|SE|3|0|Scandinavia|
        Borlänge|SE|2|1|Scandinavia|
        Falun|SE|2|1|Scandinavia|
        Gävle|SE|1|1|Scandinavia|
        Göteborg|SE|1|1|Scandinavia|
        Haparanda|SE|3|0|Scandinavia|
        Helsingborg|SE|2|1|Scandinavia|
        Jönköping|SE|2|1|Scandinavia|
        Kalix|SE|3|0|ProMods|
        Kalmar|SE|2|1|Scandinavia|
        Kapellskär|SE|3|0|Scandinavia|
        Karesuando|SE|3|0|Scandinavia|
        Karlskrona|SE|3|0|Scandinavia|
        Karlstad|SE|2|1|Scandinavia|
        Kiruna|SE|2|1|Scandinavia|
        Kristianstad|SE|3|0|ProMods|
        Linköping|SE|2|1|Scandinavia|
        Luleå|SE|2|1|Scandinavia|
        Malmö|SE|2|1|Scandinavia|
        Nynäshamn|SE|3|0|Scandinavia|
        Skellefteå|SE|2|1|Scandinavia|
        Stockholm|SE|1|1|Scandinavia|
        Sundsvall|SE|2|1|Scandinavia|
        Söderhamn|SE|3|0|ProMods|
        Södertälje|SE|3|0|Scandinavia|
        Trelleborg|SE|3|0|Scandinavia|
        Umeå|SE|2|1|Scandinavia|
        Uppsala|SE|2|1|Scandinavia|
        Visby|SE|3|0|ProMods|
        Västerås|SE|3|0|Scandinavia|
        Växjö|SE|2|1|Scandinavia|
        Ystad|SE|3|0|ProMods|
        Åre|SE|3|0|ProMods|
        Örebro|SE|3|0|Scandinavia|
        Örnsköldsvik|SE|3|0|Scandinavia|
        Östersund|SE|2|1|Scandinavia|
        Koper|SI|3|0|West Balkans|
        Ljubljana|SI|2|1|West Balkans|
        Maribor|SI|3|0|West Balkans|
        Novo Mesto|SI|3|0|West Balkans|
        Grumantbyen|SJ|3|0|ProMods|
        Hiorthhamn|SJ|3|0|ProMods|
        Longyearbyen|SJ|3|0|ProMods|
        Banská Bystrica|SK|3|0|Base game|
        Bratislava|SK|3|0|Base game|
        Košice|SK|3|0|Base game|
        Michalovce|SK|3|0|ProMods|
        Trnava|SK|3|0|ProMods|
        Zvolen|SK|3|0|ProMods|
        Edirne|TR|1|1|Road to the Black Sea|
        Tekirdağ|TR|2|1|Road to the Black Sea|
        Türkgözü|TR|3|0|ProMods|
        Çorlu|TR|3|0|ProMods|
        İstanbul|TR|1|1|Road to the Black Sea|
        Chernvitsi|UA|3|0|ProMods|
        Ivano-Frankivsk|UA|3|0|ProMods|
        Kovel|UA|3|0|ProMods|
        Lutsk|UA|3|0|ProMods|
        Lviv|UA|3|0|ProMods|
        Mukachevo|UA|3|0|ProMods|
        Novovolynsk|UA|3|0|ProMods|
        Polyanytsya|UA|3|0|ProMods|
        Sarny|UA|3|0|ProMods|
        Stryi|UA|3|0|ProMods|
        Uzhhorod|UA|3|0|ProMods|
        Varash|UA|3|0|ProMods|
        Aberdeen|UK|3|0|Base game|
        Aberystwyth|UK|3|0|ProMods|
        Antrim|UK|3|0|ProMods|
        Balivanich|UK|3|0|ProMods|
        Ballymena|UK|3|0|ProMods|
        Belfast|UK|3|0|ProMods|
        Birmingham|UK|3|0|Base game|
        Birsay|UK|3|0|ProMods|
        Broadford|UK|3|0|ProMods|
        Cairnryan|UK|3|0|ProMods|
        Cambridge|UK|3|0|Base game|
        Canterbury|UK|3|0|ProMods|
        Cardiff|UK|3|0|Base game|
        Carlisle|UK|3|0|Base game|
        Chelmsford|UK|3|0|ProMods|
        Croydon|UK|3|0|ProMods|
        Dover|UK|3|0|Base game|
        Dumfries|UK|3|0|ProMods|
        Edinburgh|UK|3|0|Base game|
        Evie|UK|3|0|ProMods|
        Exeter|UK|3|0|ProMods|
        Felixstowe|UK|3|0|Base game|
        Fishguard|UK|3|0|ProMods|
        Folkestone|UK|3|0|ProMods|
        Fort William|UK|3|0|ProMods|
        Fraserburgh|UK|3|0|ProMods|
        Glasgow|UK|2|1|Base game|
        Grimsby|UK|3|0|Base game|
        Hawes|UK|3|0|ProMods|
        Heysham|UK|3|0|ProMods|
        Holyhead|UK|3|0|ProMods|
        Hull|UK|3|0|ProMods|
        Inverness|UK|3|0|ProMods|
        Kirkwall|UK|3|0|ProMods|
        Larne|UK|3|0|ProMods|
        Lisburn|UK|3|0|ProMods|
        Liverpool|UK|3|0|Base game|
        Lochboisdale|UK|3|0|ProMods|
        London|UK|2|1|Base game|
        Londonderry|UK|3|0|ProMods|
        Manchester|UK|2|1|Base game|
        Newcastle-upon-Tyne|UK|3|0|Base game|
        Newport|UK|3|0|ProMods|
        Norwich|UK|3|0|ProMods|
        Oban|UK|3|0|ProMods|
        Perth|UK|3|0|ProMods|
        Plymouth|UK|3|0|Base game|
        Porthmadog|UK|3|0|ProMods|
        Portree|UK|3|0|ProMods|
        Portsmouth|UK|3|0|ProMods|
        Sheffield|UK|3|0|Base game|
        Southampton|UK|3|0|Base game|
        Stornoway|UK|3|0|ProMods|
        Stranraer|UK|3|0|ProMods|
        Swansea|UK|3|0|Base game|
        Tarbert|UK|3|0|ProMods|
        Thurso|UK|3|0|ProMods|
        Ullapool|UK|3|0|ProMods|
        Wick|UK|3|0|ProMods|
        Prishtinë|XK|2|1|West Balkans|
        """;

    /// <summary>The companies on ETS2's freight market, from the wiki's company table. No SCS tokens: the
    /// wiki does not carry them, and they are only used to read a company-renaming mod.</summary>
    internal static readonly AtsCompanies.Firm[] Firms =
    {
        new("AA - Auto di Alonso", "Vehicles", "Passenger vehicle retail", new[] { "IT" }, 4, ""),
        new("ACC", "Construction", "Metal processing", new[] { "ES", "IT", "PT" }, 12, ""),
        new("ACI SRL", "Logistics", "Airport logistics", new[] { "IT" }, 7, ""),
        new("AI Automotive", "Vehicles", "Vehicle parts manufacturing", new[] { "BA", "DE", "MK", "RS", "SI" }, 12, ""),
        new("APP", "Logistics", "General logistics", new[] { "ES", "PT" }, 9, ""),
        new("Adrica", "Logistics", "Port logistics", new[] { "HR" }, 3, ""),
        new("AeroBaltica", "Logistics", "Airport logistics", new[] { "EE", "FI", "LT", "LV" }, 6, ""),
        new("Agregados, S.A.", "Construction", "Concrete production", new[] { "ES", "PT" }, 4, ""),
        new("Agrominta UAB", "Food", "Farming", new[] { "LT" }, 2, ""),
        new("Agronord", "Food", "Crop farming", new[] { "DK", "NO", "SE" }, 8, ""),
        new("Alumcore", "Construction", "Metal processing", new[] { "SE" }, 1, ""),
        new("Aluxion Metal Solution", "Construction", "Metal processing", new[] { "BA", "ME" }, 4, ""),
        new("Associated Nordic Ports", "Logistics", "Port logistics", new[] { "FI", "NO", "SE" }, 6, ""),
        new("Ateria AS", "Food", "Food processing", new[] { "EE", "FI" }, 6, ""),
        new("BCP", "Vehicles", "Vehicle manufacturing", new[] { "DE", "HU", "IT", "PL", "SK", "UK" }, 8, ""),
        new("BHB - La Raffinerie", "Energy", "Fuel production", new[] { "FR" }, 2, ""),
        new("BHV", "Vehicles", "Passenger vehicle retail", new[] { "BG", "DK", "EE", "ES", "FI", "FR", "LT", "NO", "PT", "RO", "SE", "TR" }, 41, ""),
        new("BLT (Baltic Logistic Transprot)", "Logistics", "General logistics", new[] { "EE", "LT", "RU" }, 8, ""),
        new("Balkan Loco", "Logistics", "Railway logistics", new[] { "BA", "BG", "MK", "RO", "SI", "TR" }, 9, ""),
        new("Balteus Yachts", "Vehicles", "Shipbuilding", new[] { "EE", "FI", "LV", "RU" }, 4, ""),
        new("Baltic Metallurgy", "Construction", "Metal processing", new[] { "EE", "FI", "LT", "LV" }, 4, ""),
        new("Baltomorsk Woodworking Factory", "Wood", "Sawmill", new[] { "LT", "LV", "RU" }, 10, ""),
        new("Baltrak Lojistik", "Logistics", "General logistics", new[] { "TR" }, 3, ""),
        new("Betunija", "Construction", "Building materials distribution", new[] { "AL", "BA", "HR", "RS", "XK" }, 7, ""),
        new("Björk", "Wood", "Logging and sawmill", new[] { "NO", "SE" }, 9, ""),
        new("Boisserie Jean-Pierre", "Wood", "Sawmill", new[] { "FR" }, 3, ""),
        new("Borealis Shipyard", "Vehicles", "Shipbuilding", new[] { "FI", "NO" }, 3, ""),
        new("Bosfir Komerc", "Wood", "Sawmill", new[] { "BA" }, 3, ""),
        new("Brawen Transport", "Logistics", "General logistics", new[] { "BA", "GR", "MK", "RO", "RS", "SI" }, 10, ""),
        new("Byggpro", "Construction", "Building materials distribution", new[] { "FI", "NO", "SE" }, 9, ""),
        new("Bâtisse", "Construction", "Building construction", new[] { "FR" }, 11, ""),
        new("CGLA", "Construction", "Glass manufacturing", new[] { "BG", "ES", "RO", "RS" }, 6, ""),
        new("CNP", "Energy", "Fuel production", new[] { "AL", "AT", "BG", "DE", "ES", "GR", "HR", "IT", "NL", "RO", "RS" }, 26, ""),
        new("Cantera Ibérica", "Quarrying", "Quarrying", new[] { "ES", "PT" }, 6, ""),
        new("Canteras del Sur", "Quarrying", "Quarrying", new[] { "ES" }, 2, ""),
        new("Cantiere Navale", "Vehicles", "Shipbuilding", new[] { "IT" }, 3, ""),
        new("Cargotras", "Logistics", "General logistics", new[] { "IT" }, 7, ""),
        new("Casa Olivera", "Food", "Olive/crop farming", new[] { "ES" }, 4, ""),
        new("Celler Construction Group", "Construction", "Building construction", new[] { "AL", "GR", "HR", "XK" }, 5, ""),
        new("Cemeltex", "Construction", "Building construction", new[] { "BG", "EE", "LT", "LV", "RO", "RU", "TR" }, 12, ""),
        new("Cesare Supermercato", "Retail", "Grocery", new[] { "IT" }, 4, ""),
        new("Cesta, S.L.", "Retail", "Grocery", new[] { "ES" }, 8, ""),
        new("Charmey Group", "Food", "Chocolate production", new[] { "CH" }, 2, ""),
        new("Chimi", "Chemical", "Chemical storage", new[] { "FR" }, 2, ""),
        new("Christopoulos Oikodomika", "Construction", "Building materials distribution", new[] { "GR" }, 5, ""),
        new("Comoto", "Vehicles", "Vehicle manufacturing", new[] { "ES", "IT" }, 3, ""),
        new("Construcciones Elcano, S.L.", "Construction", "Building construction", new[] { "ES" }, 5, ""),
        new("Container Port", "Logistics", "Port logistics", new[] { "AL", "BE", "BG", "DE", "DK", "EE", "FI", "GR", "HR", "LT", "NL", "NO", "RO", "RU", "SE", "SI" }, 23, ""),
        new("Cortiça Prima", "Wood", "Sawmill", new[] { "PT" }, 4, ""),
        new("Costruzione di Edifici", "Construction", "Building construction", new[] { "IT" }, 8, ""),
        new("Crno Drvo", "Wood", "Logging and sawmill", new[] { "ME" }, 2, ""),
        new("DAF Trucks", "Vehicles", "Truck manufacturing and retail", new[] { "EE", "ES", "FI", "FR", "GR", "IT", "NL", "NO", "RO", "RU", "UK" }, 13, ""),
        new("Dans le Jardin", "Food", "Crop farming", new[] { "FR" }, 8, ""),
        new("Deutsche Frachthäfen", "Logistics", "Port logistics", new[] { "DE" }, 7, ""),
        new("Dimitriou A.E.", "Vehicles", "Passenger vehicle retail", new[] { "GR" }, 3, ""),
        new("Dobra Ferma", "Food", "Crop farming", new[] { "BG" }, 3, ""),
        new("DomDepo", "Construction", "Building materials distribution", new[] { "AT", "BG", "DE", "ES", "LT", "LV", "RO", "RU", "TR" }, 18, ""),
        new("Drekkar Trans", "Logistics", "General logistics", new[] { "DK", "NO", "SE" }, 10, ""),
        new("Dulcis", "Vehicles", "Vehicle manufacturing", new[] { "RO" }, 1, ""),
        new("DunaVia", "Logistics", "Port logistics", new[] { "HR", "RS" }, 3, ""),
        new("EPPA", "Food", "Food processing", new[] { "PT" }, 2, ""),
        new("Eliarchos Olive Farm", "Food", "Olive/crop farming", new[] { "GR" }, 2, ""),
        new("Engeron", "Energy", "Solar power", new[] { "ES" }, 5, ""),
        new("Eolo Lines", "Logistics", "Port logistics", new[] { "ES", "FR", "GR", "IT" }, 13, ""),
        new("Estonian Paper AS", "Wood", "Papermaking", new[] { "EE" }, 1, ""),
        new("Eumefa", "Construction", "Metal processing", new[] { "AL", "BA", "GR", "RS", "SI" }, 8, ""),
        new("EuroAcres", "Food", "Farming", new[] { "AT", "CH", "CZ", "DE", "FR", "HU", "IT", "NL", "PL", "UK" }, 31, ""),
        new("EuroGoodies", "Food", "Food distribution", new[] { "AT", "BE", "CZ", "DE", "FR", "HR", "HU", "IT", "ME", "NL", "PL", "SI", "SK", "UK" }, 38, ""),
        new("Euroflow Ports", "Logistics", "Port logistics", new[] { "BE" }, 2, ""),
        new("Evikši ZS", "Food", "Farming", new[] { "LV" }, 6, ""),
        new("Exomar", "Logistics", "General logistics", new[] { "ES", "IT", "PT" }, 10, ""),
        new("FCP", "Vehicles", "Vehicle manufacturing", new[] { "AT", "BE", "DE", "IT", "PL", "UK" }, 10, ""),
        new("FLE", "Logistics", "Airport logistics", new[] { "BG", "DE", "DK", "ES", "FR", "ME", "MK", "NO", "RO", "RS", "TR" }, 28, ""),
        new("FUI SpA", "Food", "Crop farming", new[] { "IT" }, 5, ""),
        new("Fallow Cargo", "Logistics", "General logistics", new[] { "AL", "BA", "GR", "HR", "ME", "RO", "TR" }, 10, ""),
        new("Fattoria Felice", "Food", "Livestock farming", new[] { "IT" }, 2, ""),
        new("Feldbinder", "Vehicles", "Trailer manufacturing", new[] { "DE" }, 2, ""),
        new("Finnish Tyres Oy", "Vehicles", "Tire manufacturing", new[] { "FI", "RU" }, 2, ""),
        new("Fjoste", "Construction", "Metal processing", new[] { "FI", "NO", "SE" }, 7, ""),
        new("Freyr", "Food", "Livestock farming", new[] { "DK", "FI", "NO", "SE" }, 9, ""),
        new("GNT", "Logistics", "General logistics", new[] { "FR", "LT", "LV", "NO", "SE" }, 15, ""),
        new("Gallia Ferries", "Logistics", "Port logistics", new[] { "ES", "FR" }, 2, ""),
        new("Globeur", "Logistics", "General logistics", new[] { "FR" }, 6, ""),
        new("Gomme du Monde", "Vehicles", "Tire manufacturing", new[] { "FR" }, 2, ""),
        new("Granoro", "Food", "Food processing", new[] { "DE" }, 2, ""),
        new("Hannover Expo (ITS)", "Retail", "Exposition center", new[] { "DE" }, 1, ""),
        new("Hotel Artemia", "Retail", "Hotels", new[] { "GR" }, 5, ""),
        new("Huerta del Mar Menor, S.L.", "Food", "Crop farming", new[] { "ES", "PT" }, 7, ""),
        new("Huilant", "Energy", "Fuel storage", new[] { "FR" }, 4, ""),
        new("IBP (International Baltic Petroleum)", "Energy", "Fuel production", new[] { "FI", "LT" }, 3, ""),
        new("IKA Bohag", "Retail", "Home goods", new[] { "BG", "DE", "DK", "ES", "FI", "FR", "HR", "IT", "LT", "NL", "NO", "PT", "RO", "RS", "RU", "SE" }, 49, ""),
        new("INI", "Energy", "Gas stations", new[] { "IT" }, 10, ""),
        new("ITCC", "Construction", "Metal processing", new[] { "AT", "BA", "CZ", "DE", "LU", "MK", "NL", "PL", "SI", "SK", "UK" }, 21, ""),
        new("Iberatómica", "Energy", "Nuclear power", new[] { "ES" }, 2, ""),
        new("Icaria Logistic Company", "Logistics", "Port logistics", new[] { "GR" }, 9, ""),
        new("Jastuk", "Wood", "Furniture manufacturing", new[] { "AL", "BA", "RS" }, 5, ""),
        new("Kaarfor", "Retail", "Grocery", new[] { "BG", "CZ", "DE", "FR", "HU", "IT", "PL", "RO", "TR", "UK" }, 32, ""),
        new("Kathode", "Construction", "Metal processing", new[] { "AT", "CH", "DE", "FI", "NL", "NO" }, 9, ""),
        new("Kivisydän Betoni", "Construction", "Concrete production", new[] { "FI" }, 1, ""),
        new("Konstnorr", "Construction", "Building construction", new[] { "DK", "FI", "NO", "SE" }, 19, ""),
        new("Krone", "Vehicles", "Trailer manufacturing", new[] { "DE" }, 2, ""),
        new("LkwLog GmbH", "Logistics", "General logistics", new[] { "AT", "CZ", "DE", "FR", "HU", "IT", "LU", "NL", "PL", "SK", "UK" }, 22, ""),
        new("Ladoga Auto", "Vehicles", "Vehicle manufacturing", new[] { "FI", "RU" }, 3, ""),
        new("Larus Group", "Vehicles", "Vehicle manufacturing", new[] { "SI" }, 1, ""),
        new("Lateds AS", "Food", "Food processing", new[] { "LV" }, 2, ""),
        new("Latvijas Vagonu Rūpnīca", "Vehicles", "Locomotive manufacturing", new[] { "LV" }, 2, ""),
        new("Lavish Foods", "Food", "Food processing", new[] { "ES" }, 5, ""),
        new("Lefko Cotton", "Food", "Crop farming", new[] { "GR" }, 4, ""),
        new("Libellula", "Vehicles", "Motorcycle manufacturing", new[] { "IT" }, 4, ""),
        new("Lintukainen Oy", "Wood", "Logging and sawmill", new[] { "EE", "FI" }, 13, ""),
        new("Lisette Logistics", "Logistics", "General logistics", new[] { "FR" }, 8, ""),
        new("Log n Stick Logistic", "Logistics", "General logistics", new[] { "RO", "TR" }, 5, ""),
        new("Logística Atlântica", "Logistics", "General logistics", new[] { "ES", "PT" }, 9, ""),
        new("Low Field Family Plant Farm", "Food", "Crop farming", new[] { "BA", "GR", "RO", "TR" }, 8, ""),
        new("MS Stein", "Quarrying", "Quarrying", new[] { "NO" }, 6, ""),
        new("MVM Carrière", "Quarrying", "Quarrying", new[] { "FR" }, 8, ""),
        new("Maatila Egres", "Food", "Crop farming", new[] { "FI" }, 4, ""),
        new("Marina", "Vehicles", "Ship storage", new[] { "AL", "DE", "DK", "EE", "ES", "FI", "FR", "GR", "HR", "IT", "LT", "LV", "NO", "PT", "RO", "SE", "TR" }, 39, ""),
        new("Marmo SpA", "Quarrying", "Quarrying", new[] { "IT" }, 5, ""),
        new("Medas", "Energy", "Gas stations", new[] { "GR" }, 3, ""),
        new("Metallis", "Construction", "Metal processing", new[] { "FI", "NO", "SE" }, 5, ""),
        new("Metallurgy Muromets", "Construction", "Metal processing", new[] { "RU" }, 1, ""),
        new("Mjölnir Mining", "Quarrying", "Quarrying", new[] { "FI", "SE" }, 6, ""),
        new("NBFC", "Chemical", "Chemical works", new[] { "CZ", "DE", "FR", "HU", "UK" }, 7, ""),
        new("NCH (Nordic Cargo Handling)", "Logistics", "Railway logistics", new[] { "EE", "FI", "LT", "LV", "RU" }, 6, ""),
        new("NOFEBA", "Construction", "Building materials production", new[] { "FI", "NO", "SE" }, 4, ""),
        new("NS Chemicals", "Chemical", "Chemical storage", new[] { "ES", "FI", "GR", "LT", "LV", "NO", "PT", "RU", "SE" }, 12, ""),
        new("NS Oil", "Energy", "Fuel storage", new[] { "AT", "CH", "DE", "DK", "EE", "ES", "FI", "LT", "LV", "NL", "NO", "PT", "RO", "RU", "SE", "TR" }, 35, ""),
        new("Nordic Crown", "Food", "Food processing", new[] { "DK", "NO", "SE" }, 9, ""),
        new("Nordic Stenbrott", "Quarrying", "Quarrying", new[] { "SE" }, 7, ""),
        new("Norrfood", "Retail", "Grocery", new[] { "DK", "NO", "SE" }, 18, ""),
        new("Norrsken", "Logistics", "General logistics", new[] { "DK", "NO", "SE" }, 11, ""),
        new("Norse Rail", "Logistics", "Railway logistics", new[] { "FI", "NO", "SE" }, 5, ""),
        new("Nos Pâturages", "Food", "Livestock farming", new[] { "ES", "FR" }, 6, ""),
        new("Noskonitta", "Food", "Food processing", new[] { "LT" }, 3, ""),
        new("Nucléon", "Energy", "Nuclear power", new[] { "BG", "FR", "RO" }, 7, ""),
        new("Nutri Mølle", "Food", "Food processing", new[] { "NO" }, 1, ""),
        new("Ocean Solution Group", "Vehicles", "Shipbuilding", new[] { "BG", "DE", "ES", "GR", "PT", "RO" }, 9, ""),
        new("Ortiz", "Vehicles", "Vehicle manufacturing", new[] { "ES", "PT" }, 5, ""),
        new("Oțel Impecabil", "Construction", "Metal processing", new[] { "RO" }, 6, ""),
        new("PIAC", "Vehicles", "Vehicle manufacturing", new[] { "IT", "RS" }, 6, ""),
        new("PK Medved", "Food", "Food processing", new[] { "RU" }, 2, ""),
        new("PP Chimica Italia s.r.l.", "Chemical", "Chemical works", new[] { "IT" }, 4, ""),
        new("Polar Fish", "Food", "Fish processing", new[] { "DK", "FI", "NO", "SE" }, 10, ""),
        new("Polaris Lines", "Logistics", "Port logistics and ferry operations", new[] { "DE", "DK", "EE", "FI", "LV", "NO", "SE" }, 22, ""),
        new("Port de Conteneur", "Logistics", "Port logistics", new[] { "FR" }, 2, ""),
        new("Posped", "Logistics", "General logistics", new[] { "AT", "FR", "HU", "IT", "NL", "PL", "SK", "UK" }, 16, ""),
        new("Primel", "Energy", "Gas stations", new[] { "DK", "FI", "LU", "NL", "NO", "SE" }, 12, ""),
        new("Quadrelli SpA", "Quarrying", "Quarrying", new[] { "IT" }, 3, ""),
        new("RIMAF", "Food", "Livestock farming", new[] { "MK", "RO", "TR" }, 4, ""),
        new("RT Log", "Logistics", "Railway logistics", new[] { "AT", "CH", "DE", "ES" }, 18, ""),
        new("Radus", "Construction", "Concrete production", new[] { "BA", "BG", "EE", "FI", "ME", "RS", "RU", "TR" }, 13, ""),
        new("Renar Logistik", "Logistics", "General logistics", new[] { "DK", "EE", "FI", "FR", "NO", "SE" }, 28, ""),
        new("Renat", "Wood", "Furniture manufacturing", new[] { "AT", "BG", "DE", "EE", "FI", "LT", "LV", "RO" }, 12, ""),
        new("Renor Recycling", "Logistics", "Recycling", new[] { "DK", "FI", "NO", "SE" }, 12, ""),
        new("Rock Eater Quarry", "Quarrying", "Quarrying", new[] { "BG", "GR", "ME", "MK", "RO", "RS", "TR" }, 20, ""),
        new("Rosmark", "Logistics", "General logistics", new[] { "LV", "RU" }, 6, ""),
        new("Rump", "Vehicles", "Vehicle manufacturing", new[] { "RO" }, 1, ""),
        new("S.A.L. S.R.L.", "Wood", "Sawmill", new[] { "IT" }, 4, ""),
        new("SAL (Sininen Aurinko Logistiikka)", "Logistics", "General logistics", new[] { "FI" }, 9, ""),
        new("SCS Paper", "Wood", "Papermaking", new[] { "BA", "ES", "PT", "RO", "RS", "TR" }, 9, ""),
        new("Sag & Tre Sawmill", "Wood", "Sawmill and furniture manufacturing", new[] { "NO" }, 6, ""),
        new("Sanbuilders", "Construction", "Building construction", new[] { "AL", "AT", "BA", "BE", "CH", "CZ", "DE", "DK", "FI", "GR", "HR", "HU", "LU", "NL", "NO", "PL", "RS", "SE", "UK", "XK" }, 40, ""),
        new("Scania AB", "Vehicles", "Truck manufacturing and retail", new[] { "DE", "EE", "FI", "HR", "IT", "PT", "RO", "SE", "UK" }, 12, ""),
        new("Scout Cars", "Vehicles", "Vehicle manufacturing", new[] { "CZ" }, 1, ""),
        new("SellPlan", "Retail", "Grocery", new[] { "AT", "BE", "CH", "CZ", "DE", "IT", "LU", "NL", "PL", "SK", "UK" }, 23, ""),
        new("Severoatom", "Energy", "Nuclear power", new[] { "RU" }, 1, ""),
        new("Shuttle Cola", "Food", "Beverages", new[] { "AL", "AT", "BA", "BE", "BG", "DE", "ES", "GR", "HR", "ME", "NO", "PT", "RO", "RS" }, 22, ""),
        new("Sirin Air", "Logistics", "Airport logistics", new[] { "RU" }, 1, ""),
        new("Skog Paperworks", "Wood", "Papermaking", new[] { "NO", "SE" }, 4, ""),
        new("Slava Auto", "Vehicles", "Passenger vehicle retail", new[] { "AL", "BA", "HR", "ME", "XK" }, 7, ""),
        new("Spinelli", "Vehicles", "Tire manufacturing", new[] { "ES", "IT", "RO" }, 6, ""),
        new("Sporklift Pallet Truck Manufacturer", "Vehicles", "Forklift manufacturing", new[] { "BG", "RO" }, 4, ""),
        new("Steinbruch", "Quarrying", "Quarrying", new[] { "AT", "BE", "CH", "CZ", "DE", "FR", "PL", "UK" }, 22, ""),
        new("Stokes", "Logistics", "General logistics", new[] { "AL", "AT", "BA", "CH", "DE", "FR", "HR", "NL", "PL", "SI", "SK", "UK", "XK" }, 20, ""),
        new("Stomanena Roza", "Construction", "Metal processing", new[] { "BG" }, 3, ""),
        new("Stronghold", "Construction", "Concrete production", new[] { "NL" }, 1, ""),
        new("Subse", "Food", "Food processing", new[] { "BG", "FR", "GR", "HR", "ME", "MK", "RO", "TR" }, 13, ""),
        new("Suikersmij", "Food", "Sugar production", new[] { "NL" }, 1, ""),
        new("SuperCesta", "Retail", "Grocery", new[] { "ES" }, 4, ""),
        new("Suprema", "Retail", "Grocery", new[] { "EE", "FI", "LT", "LV", "RU" }, 16, ""),
        new("Sygomidi Feed Mill", "Food", "Food processing", new[] { "GR" }, 2, ""),
        new("Syllurgy Technology", "Construction", "Metal processing", new[] { "BA", "GR", "RS" }, 7, ""),
        new("Syschema", "Chemical", "Chemical works", new[] { "BA", "GR", "HR", "RS" }, 4, ""),
        new("TDC Auto Terminal", "Vehicles", "Passenger vehicle storage", new[] { "DE", "ES", "NL", "SI" }, 7, ""),
        new("TE Logistica", "Logistics", "General logistics", new[] { "IT" }, 6, ""),
        new("TQG", "Energy", "Gas stations", new[] { "DK", "FI", "NO", "SE" }, 8, ""),
        new("TREE-ET Wood", "Wood", "Logging and sawmill", new[] { "AT", "BE", "CH", "DE", "ES", "FR", "PL", "SK", "UK" }, 24, ""),
        new("TS Atlas Container Terminal", "Logistics", "Port logistics", new[] { "ES", "PT" }, 11, ""),
        new("TTK (Teodora Transportation Company)", "Logistics", "General logistics", new[] { "BG" }, 3, ""),
        new("Terminal Container", "Logistics", "Port logistics", new[] { "IT" }, 6, ""),
        new("Tesoro Gustoso", "Food", "Food processing", new[] { "IT" }, 5, ""),
        new("The Train Foundry", "Vehicles", "Locomotive manufacturing", new[] { "BG", "ES", "HR", "RO" }, 4, ""),
        new("Timber Turtle", "Wood", "Sawmill", new[] { "RO", "RS" }, 3, ""),
        new("Trade Market Istanbul", "Logistics", "General logistics", new[] { "TR" }, 1, ""),
        new("Tradeaux", "Logistics", "General logistics", new[] { "AT", "CZ", "DE", "FR", "HU", "PL", "UK" }, 19, ""),
        new("Trameri", "Construction", "Building materials production", new[] { "AT", "CZ", "DE", "FI", "FR", "HU", "PL", "UK" }, 18, ""),
        new("TransiNet", "Logistics", "General logistics", new[] { "BE", "CZ", "DE", "HU", "IT", "PL", "UK" }, 13, ""),
        new("Transportes Caballería", "Logistics", "General logistics", new[] { "ES", "PT" }, 8, ""),
        new("Trasporti Mediterraneo", "Logistics", "General logistics", new[] { "IT" }, 5, ""),
        new("UKKO Voima", "Energy", "Nuclear power", new[] { "FI" }, 2, ""),
        new("Vanha Kivi", "Quarrying", "Quarrying", new[] { "EE", "FI", "LT", "LV", "RU" }, 7, ""),
        new("Vesna", "Food", "Food processing", new[] { "BA", "MK", "RS" }, 5, ""),
        new("Viljo Paperitehdas Oy", "Wood", "Papermaking", new[] { "FI" }, 4, ""),
        new("Villco Group", "Retail", "Grocery and food distribution", new[] { "BA", "GR", "HR", "ME", "MK", "RS", "SI", "XK" }, 19, ""),
        new("Vilniaus Popieriaus Fabrikas", "Wood", "Papermaking", new[] { "LT" }, 1, ""),
        new("Vitas Power", "Energy", "Wind turbine manufacturing", new[] { "DE", "DK", "ES", "FI", "IT", "PT", "RS" }, 16, ""),
        new("Voitureux", "Vehicles", "Vehicle manufacturing", new[] { "FR" }, 3, ""),
        new("Volvo", "Vehicles", "Truck manufacturing and retail", new[] { "BG", "DE", "ES", "FI", "FR", "IT", "LT", "LU", "NO", "RO", "SE", "UK" }, 15, ""),
        new("Väinämöinen Oy", "Construction", "Building construction", new[] { "FI" }, 3, ""),
        new("WGCC", "Chemical", "Chemical works", new[] { "BE", "DE", "DK", "FI", "FR", "NO", "PL", "SE", "SK", "UK" }, 17, ""),
        new("Wilnet Transport", "Logistics", "General logistics", new[] { "FR" }, 6, ""),
        new("Zelenye Polja OOO", "Food", "Farming", new[] { "RU" }, 2, ""),
        new("ÉCO", "Energy", "Gas stations", new[] { "FR" }, 7, ""),
        new("Õnnelik Talu", "Food", "Farming", new[] { "EE" }, 4, ""),
    };
}
