# The names ETS2 shows with "Localized city and country names" on in English (the default), against the
# local name the game's files and its other setting use. Two kinds:
#   DISPLAY - the app shows the English name for these (reported from play: Hanover, Cologne on the cargo list).
#   ACCEPT  - other English or older spellings a driver may type; looked up, not shown.
DISPLAY = {
    ('AT', 'Wien'): 'Vienna',
    ('BE', 'Brussel'): 'Brussels', ('BE', 'Antwerpen'): 'Antwerp',
    ('CH', 'Genève'): 'Geneva', ('CH', 'Zürich'): 'Zurich',
    ('CZ', 'Praha'): 'Prague',
    ('DE', 'Köln'): 'Cologne', ('DE', 'München'): 'Munich', ('DE', 'Nürnberg'): 'Nuremberg', ('DE', 'Hannover'): 'Hanover',
    ('DK', 'København'): 'Copenhagen',
    ('ES', 'Sevilla'): 'Seville', ('ES', 'València'): 'Valencia',
    ('GR', 'Athina'): 'Athens',
    ('IT', 'Firenze'): 'Florence', ('IT', 'Genova'): 'Genoa', ('IT', 'Milano'): 'Milan', ('IT', 'Napoli'): 'Naples',
    ('IT', 'Roma'): 'Rome', ('IT', 'Torino'): 'Turin', ('IT', 'Venezia'): 'Venice',
    ('LV', 'Rīga'): 'Riga',
    ('MD', 'Chişinǎu'): 'Chisinau',
    ('MT', 'Il-Belt Valletta'): 'Valletta',
    ('PL', 'Warszawa'): 'Warsaw',
    ('PT', 'Lisboa'): 'Lisbon',
    ('RO', 'București'): 'Bucharest',
    ('RS', 'Beograd'): 'Belgrade',
    ('SE', 'Göteborg'): 'Gothenburg',
    ('TR', 'İstanbul'): 'Istanbul',
    ('AL', 'Tiranë'): 'Tirana',
    ('XK', 'Prishtinë'): 'Pristina',
    ('MC', 'Monaco City'): 'Monaco',
}
ACCEPT = {
    ('DE', 'Frankfurt am Main'): ['Frankfurt'], ('DE', 'Halle'): ['Halle (Saale)', 'Halle an der Saale'],
    ('DE', 'Braunschweig'): ['Brunswick'], ('DE', 'Osnabrück'): ['Osnabrueck'],
    ('BE', 'Brussel'): ['Bruxelles'], ('BE', 'Liège'): ['Liege', 'Luik', 'Lüttich'],
    ('NL', 'Rotterdam'): [],
    ('PL', 'Kraków'): ['Cracow'], ('PL', 'Gdańsk'): ['Danzig'], ('PL', 'Wrocław'): ['Breslau'],
    ('PL', 'Szczecin'): ['Stettin'], ('PL', 'Poznań'): ['Posen'],
    ('ES', 'Zaragoza'): ['Saragossa'], ('ES', 'A Coruña'): ['La Coruña', 'Corunna'],
    ('FR', 'Marseille'): ['Marseilles'], ('FR', 'Lyon'): ['Lyons'],
    ('GR', 'Irakleio'): ['Heraklion', 'Iraklion'], ('GR', 'Patra'): ['Patras'], ('GR', 'Rodos'): ['Rhodes'],
    ('GR', 'Thessaloniki'): ['Salonica'],
    ('IT', 'Siracusa'): ['Syracuse'],
    ('CZ', 'Plzeň'): ['Pilsen'],
    ('DK', 'København'): ['Kobenhavn'],
    ('RU', 'Saint Petersburg'): ['St Petersburg', 'Sankt-Peterburg'],
    ('AL', 'Durrës'): ['Durres', 'Durazzo'], ('AL', 'Vlorë'): ['Vlora'],
    ('TR', 'Edirne'): ['Adrianople'],
    ('UA', 'Lviv'): ['Lvov', 'Lemberg'],
    ('FI', 'Turku'): ['Åbo'], ('FI', 'Helsinki'): ['Helsingfors'],
    ('NL', 'Den Haag'): ['The Hague', "'s-Gravenhage"],
    ('FR', 'Dunkerque'): ['Dunkirk'],
    ('BE', 'Gent'): ['Ghent'],
    ('DE', 'Aachen'): ['Aix-la-Chapelle'],
    # ProMods spells Storslett 'Strostlett'.
    ('NO', 'Storslett'): ['Strostlett'],
}
